/websocket_bridge:
  ros__parameters:

    dua:
      params_file_path: "/home/neo/workspace/src/websocket_bridge/websocket_bridge/params.yaml"

    autostart: true
    verbose: false

    # ======================
    # WebSocket server
    # ======================
    server:
      host: "0.0.0.0"
      port: 5000
      max_connections: 10

    # ======================
    # Topic â†’ WebSocket
    # ======================
    topics:
      - "/zero_span rf_meas_manager_interfaces/msg/ZeroSpan"
      - "/channel_power rf_meas_manager_interfaces/msg/ChannelPower"
      - "/status std_msgs/msg/String"